// <auto-generated>
//   By tools/generate-indic-tables.py from Unicode 17.0.0 (IndicPositionalCategory,
//   IndicSyllabicCategory 17.0.0) and the canonical decompositions of Python's unicodedata.
//   Do not edit: rerun the generator. See IndicReorderer.cs for what these tables mean.
// </auto-generated>
namespace UnityGameTranslator.Core.TextShaping
{
    internal static class IndicTables
    {
        internal const string UnicodeVersion = "17.0.0";

        /// <summary>Signs with a part drawn to the LEFT of the cluster they follow — sorted code points.</summary>
        internal static readonly int[] LeftSigns =
        {
            0x093F, 0x094E, 0x09BF, 0x09C7, 0x09C8, 0x09CB, 0x09CC, 0x0A3F,
            0x0ABF, 0x0B47, 0x0B48, 0x0B4B, 0x0B4C, 0x0BC6, 0x0BC7, 0x0BC8,
            0x0BCA, 0x0BCB, 0x0BCC, 0x0D46, 0x0D47, 0x0D48, 0x0D4A, 0x0D4B,
            0x0D4C, 0x0DD9, 0x0DDA, 0x0DDB, 0x0DDC, 0x0DDD, 0x0DDE, 0x0F3F,
            0x1031, 0x103C, 0x1084, 0x17BE, 0x17BF, 0x17C0, 0x17C1, 0x17C2,
            0x17C3, 0x17C4, 0x17C5, 0x1A19, 0x1A55, 0x1A6E, 0x1A6F, 0x1A70,
            0x1A71, 0x1A72, 0x1B3E, 0x1B3F, 0x1B40, 0x1B41, 0x1BA6, 0x1C27,
            0x1C28, 0x1C29, 0x1C34, 0x1C35, 0xA9BA, 0xA9BB, 0xA9BF, 0xAA2F,
            0xAA30, 0xAA34, 0xAAEB, 0xAAEE, 0x110B1, 0x1112C, 0x111B4, 0x111CE,
            0x112E1, 0x11347, 0x11348, 0x1134B, 0x1134C, 0x113C2, 0x113C5, 0x113C7,
            0x113C8, 0x11436, 0x114B1, 0x114B9, 0x114BB, 0x114BC, 0x114BE, 0x115B0,
            0x115B8, 0x115B9, 0x115BA, 0x115BB, 0x116AE, 0x1171E, 0x11726, 0x1182D,
            0x11935, 0x11937, 0x11938, 0x119D2, 0x119E4, 0x11CB1, 0x11EF5, 0x11F3E,
            0x11F3F, 0x1612A, 0x1612B,
        };

        /// <summary>Signs stored in visual order, BEFORE their consonant (Visual_Order_Left) — sorted code points. Never moved; a word never ends on one.</summary>
        internal static readonly int[] VisualOrderLeft =
        {
            0x0E40, 0x0E41, 0x0E42, 0x0E43, 0x0E44, 0x0EC0, 0x0EC1, 0x0EC2,
            0x0EC3, 0x0EC4, 0x19B5, 0x19B6, 0x19B7, 0x19BA, 0xAAB5, 0xAAB6,
            0xAAB9, 0xAABB, 0xAABC,
        };

        /// <summary>Base consonants: what a cluster is built on — inclusive ranges, sorted, as (first, last) pairs.</summary>
        internal static readonly int[] BaseRanges =
        {
            0x002D, 0x002D, 0x00A0, 0x00A0, 0x00D7, 0x00D7, 0x0915, 0x0939,
            0x0958, 0x095F, 0x0978, 0x0980, 0x0995, 0x09A8, 0x09AA, 0x09B0,
            0x09B2, 0x09B2, 0x09B6, 0x09B9, 0x09CE, 0x09CE, 0x09DC, 0x09DD,
            0x09DF, 0x09DF, 0x09F0, 0x09F1, 0x0A15, 0x0A28, 0x0A2A, 0x0A30,
            0x0A32, 0x0A33, 0x0A35, 0x0A36, 0x0A38, 0x0A39, 0x0A59, 0x0A5C,
            0x0A5E, 0x0A5E, 0x0A72, 0x0A73, 0x0A95, 0x0AA8, 0x0AAA, 0x0AB0,
            0x0AB2, 0x0AB3, 0x0AB5, 0x0AB9, 0x0AF9, 0x0AF9, 0x0B15, 0x0B28,
            0x0B2A, 0x0B30, 0x0B32, 0x0B33, 0x0B35, 0x0B39, 0x0B5C, 0x0B5D,
            0x0B5F, 0x0B5F, 0x0B71, 0x0B71, 0x0B95, 0x0B95, 0x0B99, 0x0B9A,
            0x0B9C, 0x0B9C, 0x0B9E, 0x0B9F, 0x0BA3, 0x0BA4, 0x0BA8, 0x0BAA,
            0x0BAE, 0x0BB9, 0x0C15, 0x0C28, 0x0C2A, 0x0C39, 0x0C58, 0x0C5A,
            0x0C5D, 0x0C5D, 0x0C95, 0x0CA8, 0x0CAA, 0x0CB3, 0x0CB5, 0x0CB9,
            0x0CDD, 0x0CDE, 0x0CF1, 0x0CF2, 0x0D15, 0x0D3A, 0x0D4E, 0x0D4E,
            0x0D54, 0x0D56, 0x0D7A, 0x0D7F, 0x0D9A, 0x0DB1, 0x0DB3, 0x0DBB,
            0x0DBD, 0x0DBD, 0x0DC0, 0x0DC6, 0x0E01, 0x0E2E, 0x0E81, 0x0E82,
            0x0E84, 0x0E84, 0x0E86, 0x0E8A, 0x0E8C, 0x0EA3, 0x0EA5, 0x0EA5,
            0x0EA7, 0x0EAE, 0x0EDC, 0x0EDF, 0x0F40, 0x0F47, 0x0F49, 0x0F6C,
            0x0F88, 0x0F8C, 0x1000, 0x1020, 0x103F, 0x103F, 0x104B, 0x104B,
            0x104E, 0x104E, 0x1050, 0x1051, 0x105A, 0x105D, 0x1061, 0x1061,
            0x1065, 0x1066, 0x106E, 0x1070, 0x1075, 0x1081, 0x108E, 0x108E,
            0x1703, 0x1711, 0x171F, 0x171F, 0x1723, 0x1731, 0x1743, 0x1751,
            0x1763, 0x176C, 0x176E, 0x1770, 0x1780, 0x17A2, 0x1900, 0x191E,
            0x1950, 0x1962, 0x1980, 0x19AB, 0x1A00, 0x1A16, 0x1A20, 0x1A4C,
            0x1A53, 0x1A54, 0x1A5A, 0x1A5A, 0x1B13, 0x1B33, 0x1B45, 0x1B4C,
            0x1B8A, 0x1BA0, 0x1BAE, 0x1BAF, 0x1BBB, 0x1BBD, 0x1BC0, 0x1BE3,
            0x1C00, 0x1C23, 0x1C4D, 0x1C4F, 0x1CF2, 0x1CF3, 0x1CF5, 0x1CF6,
            0x1CFA, 0x1CFA, 0x2010, 0x2014, 0x25CC, 0x25CC, 0xA807, 0xA80A,
            0xA80C, 0xA822, 0xA840, 0xA85D, 0xA862, 0xA865, 0xA869, 0xA870,
            0xA872, 0xA872, 0xA892, 0xA8B3, 0xA90A, 0xA921, 0xA930, 0xA946,
            0xA989, 0xA98B, 0xA98F, 0xA9B2, 0xA9E0, 0xA9E4, 0xA9E7, 0xA9EF,
            0xA9FA, 0xA9FE, 0xAA06, 0xAA28, 0xAA60, 0xAA6F, 0xAA71, 0xAA76,
            0xAA7A, 0xAA7A, 0xAA7E, 0xAAAF, 0xAAE2, 0xAAEA, 0xABC0, 0xABCD,
            0xABD0, 0xABD0, 0xABD2, 0xABDA, 0x10A00, 0x10A00, 0x10A10, 0x10A13,
            0x10A15, 0x10A17, 0x10A19, 0x10A35, 0x11003, 0x11004, 0x11013, 0x11037,
            0x11075, 0x11075, 0x1108D, 0x110AF, 0x11107, 0x11126, 0x11144, 0x11144,
            0x11147, 0x11147, 0x11155, 0x11172, 0x11191, 0x111B2, 0x111C2, 0x111C3,
            0x11208, 0x11211, 0x11213, 0x1122B, 0x1123F, 0x1123F, 0x11284, 0x11286,
            0x11288, 0x11288, 0x1128A, 0x1128D, 0x1128F, 0x1129D, 0x1129F, 0x112A8,
            0x112BA, 0x112DE, 0x11315, 0x11328, 0x1132A, 0x11330, 0x11332, 0x11333,
            0x11335, 0x11339, 0x11392, 0x113B5, 0x113D1, 0x113D1, 0x1140E, 0x11434,
            0x11460, 0x11461, 0x1148F, 0x114AF, 0x1158E, 0x115AE, 0x1160E, 0x1162F,
            0x1168A, 0x116AA, 0x116B8, 0x116B8, 0x11700, 0x1171A, 0x11740, 0x11746,
            0x1180A, 0x1182B, 0x1190C, 0x11913, 0x11915, 0x11916, 0x11918, 0x1192F,
            0x1193F, 0x1193F, 0x11941, 0x11941, 0x119AE, 0x119D0, 0x11A00, 0x11A00,
            0x11A0B, 0x11A32, 0x11A3A, 0x11A3A, 0x11A3F, 0x11A3F, 0x11A45, 0x11A45,
            0x11A50, 0x11A50, 0x11A5C, 0x11A89, 0x11C0E, 0x11C2E, 0x11C72, 0x11C8F,
            0x11D0C, 0x11D30, 0x11D46, 0x11D46, 0x11D6C, 0x11D89, 0x11EE0, 0x11EF2,
            0x11F02, 0x11F02, 0x11F12, 0x11F33, 0x16101, 0x1611D, 0x16D43, 0x16D62,
        };

        /// <summary>Binders: a virama or stacker joining two bases into one cluster — inclusive ranges, sorted, as (first, last) pairs.</summary>
        internal static readonly int[] BinderRanges =
        {
            0x094D, 0x094D, 0x09CD, 0x09CD, 0x0A4D, 0x0A4D, 0x0ACD, 0x0ACD,
            0x0B4D, 0x0B4D, 0x0BCD, 0x0BCD, 0x0C4D, 0x0C4D, 0x0CCD, 0x0CCD,
            0x0D4D, 0x0D4D, 0x0DCA, 0x0DCA, 0x1039, 0x1039, 0x17D2, 0x17D2,
            0x1A60, 0x1A60, 0x1B44, 0x1B44, 0x1BAB, 0x1BAB, 0xA806, 0xA806,
            0xA8C4, 0xA8C4, 0xA9C0, 0xA9C0, 0xAAF6, 0xAAF6, 0x10A3F, 0x10A3F,
            0x11046, 0x11046, 0x110B9, 0x110B9, 0x11133, 0x11133, 0x111C0, 0x111C0,
            0x11235, 0x11235, 0x1134D, 0x1134D, 0x113D0, 0x113D0, 0x11442, 0x11442,
            0x114C2, 0x114C2, 0x115BF, 0x115BF, 0x1163F, 0x1163F, 0x116B6, 0x116B6,
            0x11839, 0x11839, 0x1193E, 0x1193E, 0x119E0, 0x119E0, 0x11A47, 0x11A47,
            0x11A99, 0x11A99, 0x11C3F, 0x11C3F, 0x11D45, 0x11D45, 0x11D97, 0x11D97,
            0x11F42, 0x11F42,
        };

        /// <summary>What attaches to a base (nukta, medials, killers, joiners...) — inclusive ranges, sorted, as (first, last) pairs.</summary>
        internal static readonly int[] AttachRanges =
        {
            0x093C, 0x093C, 0x09BC, 0x09BC, 0x0A3C, 0x0A3C, 0x0A71, 0x0A71,
            0x0A75, 0x0A75, 0x0ABC, 0x0ABC, 0x0AFB, 0x0AFB, 0x0AFD, 0x0AFF,
            0x0B3C, 0x0B3C, 0x0C3C, 0x0C3C, 0x0CBC, 0x0CBC, 0x0D3B, 0x0D3C,
            0x0E3A, 0x0E3A, 0x0E4C, 0x0E4C, 0x0E4E, 0x0E4E, 0x0EBA, 0x0EBA,
            0x0EBC, 0x0EBD, 0x0F39, 0x0F39, 0x0F84, 0x0F84, 0x0F8D, 0x0F97,
            0x0F99, 0x0FBC, 0x103A, 0x103E, 0x105E, 0x1060, 0x1082, 0x1082,
            0x1714, 0x1715, 0x1734, 0x1734, 0x17C9, 0x17CA, 0x17CC, 0x17CD,
            0x17D1, 0x17D1, 0x1929, 0x192B, 0x1930, 0x1931, 0x1933, 0x1939,
            0x19C1, 0x19C7, 0x1A55, 0x1A59, 0x1A5B, 0x1A5E, 0x1A7A, 0x1A7A,
            0x1B03, 0x1B03, 0x1B34, 0x1B34, 0x1B81, 0x1B81, 0x1BA1, 0x1BA3,
            0x1BAA, 0x1BAA, 0x1BAC, 0x1BAD, 0x1BBE, 0x1BBF, 0x1BE6, 0x1BE6,
            0x1BF0, 0x1BF3, 0x1C24, 0x1C25, 0x1C2D, 0x1C33, 0x1C37, 0x1C37,
            0x200C, 0x200D, 0xA82C, 0xA82C, 0xA867, 0xA868, 0xA871, 0xA871,
            0xA8B4, 0xA8B4, 0xA94F, 0xA953, 0xA982, 0xA982, 0xA9B3, 0xA9B3,
            0xA9BD, 0xA9BF, 0xAA33, 0xAA36, 0xAA40, 0xAA4D, 0xABDB, 0xABE2,
            0xABED, 0xABED, 0x10A38, 0x10A3A, 0x11070, 0x11070, 0x110BA, 0x110BA,
            0x11134, 0x11134, 0x11173, 0x11173, 0x111CA, 0x111CA, 0x11236, 0x11237,
            0x112E9, 0x112EA, 0x1133B, 0x1133C, 0x113CE, 0x113CF, 0x113D2, 0x113D2,
            0x11446, 0x11446, 0x114C3, 0x114C3, 0x115C0, 0x115C0, 0x116B7, 0x116B7,
            0x1171D, 0x1171F, 0x1172B, 0x1172B, 0x1183A, 0x1183A, 0x1193D, 0x1193D,
            0x11940, 0x11940, 0x11942, 0x11943, 0x11A34, 0x11A34, 0x11A3B, 0x11A3E,
            0x11A8A, 0x11A95, 0x11A98, 0x11A98, 0x11C92, 0x11CA7, 0x11CA9, 0x11CAF,
            0x11D42, 0x11D42, 0x11D44, 0x11D44, 0x11D47, 0x11D47, 0x11F41, 0x11F41,
            0x11F5A, 0x11F5A, 0x1612A, 0x1612C, 0x1612E, 0x1612F, 0x16D6B, 0x16D6C,
        };

        /// <summary>Joiners allowed between a binder and the next base — inclusive ranges, sorted, as (first, last) pairs.</summary>
        internal static readonly int[] JoinerRanges =
        {
            0x200C, 0x200D,
        };

        /// <summary>
        /// Two-part signs and their parts: the first part is the one that moves, the rest stay
        /// where the sign was. Flattened as (sign, count, parts...), sorted by sign.
        /// </summary>
        internal static readonly int[] Splits =
        {
            0x09CB, 2, 0x09C7, 0x09BE,
            0x09CC, 2, 0x09C7, 0x09D7,
            0x0B48, 2, 0x0B47, 0x0B56,
            0x0B4B, 2, 0x0B47, 0x0B3E,
            0x0B4C, 2, 0x0B47, 0x0B57,
            0x0BCA, 2, 0x0BC6, 0x0BBE,
            0x0BCB, 2, 0x0BC7, 0x0BBE,
            0x0BCC, 2, 0x0BC6, 0x0BD7,
            0x0D4A, 2, 0x0D46, 0x0D3E,
            0x0D4B, 2, 0x0D47, 0x0D3E,
            0x0D4C, 2, 0x0D46, 0x0D57,
            0x0DDA, 2, 0x0DD9, 0x0DCA,
            0x0DDC, 2, 0x0DD9, 0x0DCF,
            0x0DDD, 3, 0x0DD9, 0x0DCF, 0x0DCA,
            0x0DDE, 2, 0x0DD9, 0x0DDF,
            0x17C4, 2, 0x17C1, 0x17B6,
            0x1B40, 2, 0x1B3E, 0x1B35,
            0x1B41, 2, 0x1B3F, 0x1B35,
            0x1134B, 2, 0x11347, 0x1133E,
            0x1134C, 2, 0x11347, 0x11357,
            0x114BB, 2, 0x114B9, 0x114BA,
            0x114BC, 2, 0x114B9, 0x114B0,
            0x114BE, 2, 0x114B9, 0x114BD,
            0x115BA, 2, 0x115B8, 0x115AF,
            0x115BB, 2, 0x115B9, 0x115AF,
            0x11938, 2, 0x11935, 0x11930,
        };

        /// <summary>
        /// Indic_Syllabic_Category and Indic_Positional_Category of every code point from
        /// U+0900 to U+0DFF (the classic Indic blocks the OpenType shaper covers), one byte
        /// each, as indices into the name constants below. Unlisted code points are Other / NA.
        /// </summary>
        internal const int IndicFirst = 0x0900, IndicLast = 0x0DFF;

        internal static class Syllabic
        {
            internal const byte Avagraha = 0;
            internal const byte Bindu = 1;
            internal const byte Brahmi_Joining_Number = 2;
            internal const byte Cantillation_Mark = 3;
            internal const byte Consonant = 4;
            internal const byte Consonant_Dead = 5;
            internal const byte Consonant_Final = 6;
            internal const byte Consonant_Head_Letter = 7;
            internal const byte Consonant_Initial_Postfixed = 8;
            internal const byte Consonant_Killer = 9;
            internal const byte Consonant_Medial = 10;
            internal const byte Consonant_Placeholder = 11;
            internal const byte Consonant_Preceding_Repha = 12;
            internal const byte Consonant_Prefixed = 13;
            internal const byte Consonant_Subjoined = 14;
            internal const byte Consonant_Succeeding_Repha = 15;
            internal const byte Consonant_With_Stacker = 16;
            internal const byte Gemination_Mark = 17;
            internal const byte Invisible_Stacker = 18;
            internal const byte Joiner = 19;
            internal const byte Modifying_Letter = 20;
            internal const byte Non_Joiner = 21;
            internal const byte Nukta = 22;
            internal const byte Number = 23;
            internal const byte Number_Joiner = 24;
            internal const byte Other = 25;
            internal const byte Pure_Killer = 26;
            internal const byte Register_Shifter = 27;
            internal const byte Reordering_Killer = 28;
            internal const byte Syllable_Modifier = 29;
            internal const byte Tone_Letter = 30;
            internal const byte Tone_Mark = 31;
            internal const byte Virama = 32;
            internal const byte Visarga = 33;
            internal const byte Vowel = 34;
            internal const byte Vowel_Dependent = 35;
            internal const byte Vowel_Independent = 36;
        }

        internal static class Positional
        {
            internal const byte Bottom = 0;
            internal const byte Bottom_And_Left = 1;
            internal const byte Bottom_And_Right = 2;
            internal const byte Left = 3;
            internal const byte Left_And_Right = 4;
            internal const byte NA = 5;
            internal const byte Overstruck = 6;
            internal const byte Right = 7;
            internal const byte Top = 8;
            internal const byte Top_And_Bottom = 9;
            internal const byte Top_And_Bottom_And_Left = 10;
            internal const byte Top_And_Bottom_And_Right = 11;
            internal const byte Top_And_Left = 12;
            internal const byte Top_And_Left_And_Right = 13;
            internal const byte Top_And_Right = 14;
            internal const byte Visual_Order_Left = 15;
        }

        internal static readonly byte[] SyllabicOf =
        {
            1, 1, 1, 33, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 35, 35, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 32, 35, 35, 25, 3, 3, 25, 25, 35, 35, 35, 4, 4, 4, 4, 4, 4, 4, 4,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 36, 36, 36, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4,
            11, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 36, 36, 25, 25, 36, 36, 25, 25, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 25, 4, 25, 25, 25, 4, 4, 4, 4, 25, 25, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 25, 25, 35, 35, 25, 25, 35, 35, 32, 5, 25, 25, 25, 25, 25, 25, 25, 25, 35, 25, 25, 25, 25, 4, 4, 25, 4,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 4, 4, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 1, 25, 29, 25,
            25, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 25, 25, 25, 25, 36, 36, 25, 25, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 25, 4, 4, 25, 4, 4, 25, 25, 22, 25, 35, 35,
            35, 35, 35, 25, 25, 25, 25, 35, 35, 25, 25, 35, 35, 32, 25, 25, 25, 3, 25, 25, 25, 25, 25, 25, 25, 4, 4, 4, 4, 25, 4, 25,
            25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 1, 17, 11, 11, 25, 10, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            25, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 36, 36, 36, 25, 36, 36, 36, 25, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 25, 4, 4, 4, 4, 4, 25, 25, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 35, 25, 35, 35, 35, 25, 35, 35, 32, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 4, 3, 17, 3, 22, 22, 22,
            25, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 36, 36, 25, 25, 36, 36, 25, 25, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 25, 4, 4, 4, 4, 4, 25, 25, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 25, 25, 35, 35, 25, 25, 35, 35, 32, 25, 25, 25, 25, 25, 25, 25, 35, 35, 35, 25, 25, 25, 25, 4, 4, 25, 4,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 4, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            25, 25, 1, 20, 25, 36, 36, 36, 36, 36, 36, 25, 25, 25, 36, 36, 36, 25, 36, 36, 36, 4, 25, 25, 25, 4, 4, 25, 4, 25, 4, 4,
            25, 25, 25, 4, 4, 25, 25, 25, 4, 4, 4, 25, 25, 25, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 25, 25, 25, 35, 35,
            35, 35, 35, 25, 25, 25, 35, 35, 35, 25, 35, 35, 35, 32, 25, 25, 25, 25, 25, 25, 25, 25, 25, 35, 25, 25, 25, 25, 25, 25, 25, 25,
            25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            1, 1, 1, 33, 1, 36, 36, 36, 36, 36, 36, 36, 36, 25, 36, 36, 36, 25, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 25, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 25, 35, 35, 35, 25, 35, 35, 35, 32, 25, 25, 25, 25, 25, 25, 25, 35, 35, 25, 4, 4, 4, 25, 25, 5, 25, 25,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            1, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 36, 36, 25, 36, 36, 36, 25, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 25, 25, 22, 0, 35, 35,
            35, 35, 35, 35, 35, 25, 35, 35, 35, 25, 35, 35, 35, 32, 25, 25, 25, 25, 25, 25, 25, 35, 35, 25, 25, 25, 25, 25, 25, 5, 4, 25,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 16, 16, 1, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
            1, 1, 1, 33, 1, 36, 36, 36, 36, 36, 36, 36, 36, 25, 36, 36, 36, 25, 36, 36, 36, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 26, 26, 0, 35, 35,
            35, 35, 35, 35, 35, 25, 35, 35, 35, 25, 35, 35, 35, 32, 12, 25, 25, 25, 25, 25, 5, 5, 5, 35, 25, 25, 25, 25, 25, 25, 25, 36,
            36, 36, 35, 35, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 5, 5, 5, 5, 5, 5,
            25, 1, 1, 33, 25, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 25, 25, 25, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 4, 4, 4, 4, 4, 4, 4, 4, 25, 4, 25, 25,
            4, 4, 4, 4, 4, 4, 4, 25, 25, 25, 32, 25, 25, 25, 25, 35, 35, 35, 35, 35, 35, 25, 35, 25, 35, 35, 35, 35, 35, 35, 35, 35,
            25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 35, 35, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
        };

        internal static readonly byte[] PositionalOf =
        {
            8, 8, 8, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 7, 0, 5, 7, 3,
            7, 0, 0, 0, 0, 8, 8, 8, 8, 7, 7, 7, 7, 0, 3, 7, 5, 8, 0, 5, 5, 8, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 8, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 7, 3,
            7, 0, 0, 0, 0, 5, 5, 3, 3, 5, 5, 4, 4, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5,
            5, 8, 8, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 7, 3,
            7, 0, 0, 5, 5, 5, 5, 8, 8, 5, 5, 8, 8, 0, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 8, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 8, 8, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 7, 3,
            7, 0, 0, 0, 0, 8, 5, 8, 8, 14, 5, 7, 7, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 8, 8, 8, 8, 8,
            5, 8, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 7, 8,
            7, 0, 0, 0, 0, 5, 5, 3, 12, 5, 5, 4, 13, 0, 5, 5, 5, 5, 5, 5, 5, 8, 8, 14, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7,
            8, 7, 7, 5, 5, 5, 3, 3, 3, 5, 4, 4, 4, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            8, 7, 7, 7, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 8, 8,
            8, 7, 7, 7, 7, 5, 8, 8, 9, 5, 8, 8, 8, 8, 5, 5, 5, 5, 5, 5, 5, 8, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 8, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 7, 8,
            14, 7, 7, 7, 7, 5, 8, 14, 14, 5, 14, 14, 8, 8, 5, 5, 5, 5, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            8, 8, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 8, 5, 7, 7,
            7, 0, 0, 0, 0, 5, 3, 3, 3, 5, 4, 4, 4, 8, 8, 5, 5, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 8, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 7, 7, 7, 8, 8, 0, 5, 0, 5, 7, 3, 12, 3, 4, 13, 4, 7,
            5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        };

        /// <summary>
        /// Full canonical decompositions of U+0900..U+0DFF, flattened as (code point, count,
        /// parts...), sorted by code point — everything Unicode takes apart, exclusions included.
        /// </summary>
        internal static readonly int[] Decompositions =
        {
            0x0929, 2, 0x0928, 0x093C,
            0x0931, 2, 0x0930, 0x093C,
            0x0934, 2, 0x0933, 0x093C,
            0x0958, 2, 0x0915, 0x093C,
            0x0959, 2, 0x0916, 0x093C,
            0x095A, 2, 0x0917, 0x093C,
            0x095B, 2, 0x091C, 0x093C,
            0x095C, 2, 0x0921, 0x093C,
            0x095D, 2, 0x0922, 0x093C,
            0x095E, 2, 0x092B, 0x093C,
            0x095F, 2, 0x092F, 0x093C,
            0x09CB, 2, 0x09C7, 0x09BE,
            0x09CC, 2, 0x09C7, 0x09D7,
            0x09DC, 2, 0x09A1, 0x09BC,
            0x09DD, 2, 0x09A2, 0x09BC,
            0x09DF, 2, 0x09AF, 0x09BC,
            0x0A33, 2, 0x0A32, 0x0A3C,
            0x0A36, 2, 0x0A38, 0x0A3C,
            0x0A59, 2, 0x0A16, 0x0A3C,
            0x0A5A, 2, 0x0A17, 0x0A3C,
            0x0A5B, 2, 0x0A1C, 0x0A3C,
            0x0A5E, 2, 0x0A2B, 0x0A3C,
            0x0B48, 2, 0x0B47, 0x0B56,
            0x0B4B, 2, 0x0B47, 0x0B3E,
            0x0B4C, 2, 0x0B47, 0x0B57,
            0x0B5C, 2, 0x0B21, 0x0B3C,
            0x0B5D, 2, 0x0B22, 0x0B3C,
            0x0B94, 2, 0x0B92, 0x0BD7,
            0x0BCA, 2, 0x0BC6, 0x0BBE,
            0x0BCB, 2, 0x0BC7, 0x0BBE,
            0x0BCC, 2, 0x0BC6, 0x0BD7,
            0x0C48, 2, 0x0C46, 0x0C56,
            0x0CC0, 2, 0x0CBF, 0x0CD5,
            0x0CC7, 2, 0x0CC6, 0x0CD5,
            0x0CC8, 2, 0x0CC6, 0x0CD6,
            0x0CCA, 2, 0x0CC6, 0x0CC2,
            0x0CCB, 3, 0x0CC6, 0x0CC2, 0x0CD5,
            0x0D4A, 2, 0x0D46, 0x0D3E,
            0x0D4B, 2, 0x0D47, 0x0D3E,
            0x0D4C, 2, 0x0D46, 0x0D57,
            0x0DDA, 2, 0x0DD9, 0x0DCA,
            0x0DDC, 2, 0x0DD9, 0x0DCF,
            0x0DDD, 3, 0x0DD9, 0x0DCF, 0x0DCA,
            0x0DDE, 2, 0x0DD9, 0x0DDF,
        };
    }
}
