using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameTranslator.Core.Rasterizer;
using UnityGameTranslator.Core.TextShaping;

namespace UnityGameTranslator.Core.Checks
{
    /// <summary>
    /// The Indic shaper against HarfBuzz. Two layers:
    ///
    /// 1. Seventeen Devanagari words, each with what it exercises written next to it — the
    ///    readable account of what the shaper does. Expected values are HarfBuzz 14.4's
    ///    output for the same word and font (Noto Sans Devanagari), recorded 2026-09-03 with
    ///    uharfbuzz at 1000 units per em: glyph id, then (advance, x offset, y offset).
    /// 2. TestData/Shaping/*.txt — every shaped script, several hundred words, one file per
    ///    script (and per old-specification font variant), generated by tools/shaping-oracle/
    ///    harfbuzz-expectations.py from the fonts in TestData/Fonts; each file's first line
    ///    names its font and whether the script runs right to left. What they prove is
    ///    agreement with the reference shaper the fonts were built against, word by word,
    ///    glyph by glyph, unit by unit.
    ///
    /// A failure here names the word, our output and HarfBuzz's — enough to open the font's
    /// tables (fontTools) and see which rule the two read differently.
    /// </summary>
    internal static class IndicShaperChecks
    {
        private static readonly (string word, string what, string expected)[] Cases =
        {
            ("क्ष",        "akhand conjunct",                              "90(717,0,0)"),
            ("कि",         "pre-base matra reordered before its consonant", "542(259,0,0) 56(768,0,0)"),
            ("किं",        "…with an anusvara: the matra takes a variant",  "557(259,0,0) 56(768,0,0) 759(0,0,0)"),
            ("प्रिय",      "half form, rakar, matra before the cluster",    "543(259,0,0) 309(569,0,0) 81(580,0,0)"),
            ("कर्म",       "reph moved after the base",                     "56(768,0,0) 80(598,0,0) 503(0,0,0)"),
            ("हिन्दी",     "two syllables, half form, ii matra",            "541(259,0,0) 88(531,0,0) 245(309,0,0) 73(531,0,0) 33(259,0,0)"),
            ("अतिरिक्त",   "independent vowel, two i matras, half form",    "5(764,0,0) 542(259,0,0) 71(570,0,0) 539(259,0,0) 82(409,0,0) 232(536,0,0) 71(570,0,0)"),
            ("दिल्ली",     "half la before la",                             "541(259,0,0) 73(531,0,0) 252(451,0,0) 83(678,0,0) 33(259,0,0)"),
            ("कृपया",      "vocalic r below the base (mark positioning)",   "56(768,0,0) 36(0,-221,0) 76(568,0,0) 81(580,0,0) 31(259,0,0)"),
            ("कैं",        "ai matra + anusvara ligated, positioned",       "56(768,0,0) 514(0,-221,0)"),
            ("क्रम",       "rakar: ka + ra conjunct",                       "295(768,0,0) 80(598,0,0)"),
            ("रुपया",      "ra + u ligature",                               "490(598,0,0) 76(568,0,0) 81(580,0,0) 31(259,0,0)"),
            ("विकल्प",     "three syllables",                               "542(259,0,0) 84(556,0,0) 56(768,0,0) 252(429,0,0) 76(568,0,0)"),
            ("ट्रक",       "below-base ra on tta, positioned",              "66(504,0,0) 505(0,-34,0) 56(768,0,0)"),
            ("शक्ति",      "matra inside a word, after a half form",        "85(680,0,0) 552(259,0,0) 232(536,0,0) 71(570,0,0)"),
            ("सर्वोत्तम",  "reph after a post-base matra, tta conjunct",    "87(676,0,0) 84(556,0,0) 31(259,0,0) 511(0,0,0) 439(691,0,0) 80(598,0,0)"),
            ("र्",         "ra + halant alone: no reph",                    "82(409,0,0) 103(0,0,0)"),
            ("अा",         "forbidden vowel sequence: a dotted circle between", "5(764,0,0) 763(510,0,0) 31(259,0,0)"),
        };

        public static void Run(Action<bool, string, string> check)
        {
            string fontsDir = Path.Combine(AppContext.BaseDirectory, "TestData", "Fonts");
            string devanagari = Path.Combine(fontsDir, "NotoSansDevanagari.ttf");
            if (!File.Exists(devanagari)) { check(false, "check font present", devanagari); return; }
            var font = new TtfShapingFont(new TtfParser(File.ReadAllBytes(devanagari)));

            check(IndicShaper.NeedsShaping("हिन्दी") && !IndicShaper.NeedsShaping("Hello") && !IndicShaper.NeedsShaping("สวัสดี"),
                "NeedsShaping: Devanagari yes, Latin and Thai no", "");

            foreach (var (word, what, expected) in Cases)
                Compare(check, font, word, expected, word + " — " + what);

            // Latin passes through untouched: one glyph per character, cmap and advance only.
            var latin = IndicShaper.Shape("Ab", font);
            check(latin.Count == 2 && latin[0].Glyph == font.GlyphIndex('A') && latin[1].Glyph == font.GlyphIndex('b')
                  && latin[0].XAdvance == font.AdvanceWidth(latin[0].Glyph),
                "Latin: cmap glyphs, no shaping", Describe(latin));

            // Every script, from the oracle's files: one line per file in the report, every
            // word compared, the first disagreements named. The file's header says which font
            // it was made with and whether the script runs right to left.
            string shapingDir = Path.Combine(AppContext.BaseDirectory, "TestData", "Shaping");
            if (!Directory.Exists(shapingDir)) { check(false, "TestData/Shaping present", shapingDir); return; }
            var files = Directory.GetFiles(shapingDir, "*.txt");
            Array.Sort(files, StringComparer.Ordinal);
            foreach (string file in files)
            {
                string script = Path.GetFileNameWithoutExtension(file);
                var lines = File.ReadAllLines(file, Encoding.UTF8);
                if (!TryReadHeader(lines.Length > 0 ? lines[0] : "", out string fontName, out bool rightToLeft))
                {
                    check(false, script + ": header names the font", lines.Length > 0 ? lines[0] : "(empty file)");
                    continue;
                }
                string fontPath = Path.Combine(fontsDir, fontName);
                if (!File.Exists(fontPath)) { check(false, script + ": font present", fontPath); continue; }
                var scriptFont = new TtfShapingFont(new TtfParser(File.ReadAllBytes(fontPath)));
                int words = 0;
                var failures = new List<string>();
                foreach (string line in lines)
                {
                    if (line.Length == 0 || line[0] == '#') continue;
                    int tab = line.IndexOf('\t');
                    if (tab < 0) continue;
                    string word = line.Substring(0, tab), expected = line.Substring(tab + 1);
                    words++;
                    string got;
                    try
                    {
                        var shaped = OpenTypeShaping.Shape(word, scriptFont);
                        // Our output is logical order; HarfBuzz's is visual — the reverse, for a
                        // right-to-left script (the RTL composer does that reversal in the mod).
                        if (rightToLeft) shaped.Reverse();
                        got = Describe(shaped);
                    }
                    catch (Exception ex) { got = "threw " + ex.GetType().Name + ": " + ex.Message; }
                    if (got != expected) failures.Add(word + ": got " + got + " / HarfBuzz " + expected);
                }
                check(failures.Count == 0, script + ": " + words + " words against HarfBuzz",
                    failures.Count == 0 ? "= HarfBuzz, every glyph and unit (" + fontName + ")" : failures.Count + " differ — " + string.Join(" | ", failures.GetRange(0, Math.Min(3, failures.Count))));
            }
        }

        /// <summary>The oracle's header: "# font=NAME.ttf rtl=0|1 …".</summary>
        private static bool TryReadHeader(string line, out string fontName, out bool rightToLeft)
        {
            fontName = null; rightToLeft = false;
            if (!line.StartsWith("#")) return false;
            foreach (string token in line.Substring(1).Split(' '))
            {
                if (token.StartsWith("font=")) fontName = token.Substring(5);
                else if (token.StartsWith("rtl=")) rightToLeft = token.Substring(4) == "1";
            }
            return !string.IsNullOrEmpty(fontName);
        }

        private static void Compare(Action<bool, string, string> check, IShapingFont font, string word, string expected, string what)
        {
            string got;
            try { got = Describe(IndicShaper.Shape(word, font)); }
            catch (Exception ex) { got = "threw " + ex.GetType().Name + ": " + ex.Message; }
            check(got == expected, what, got == expected ? "= HarfBuzz" : "got " + got + " / HarfBuzz " + expected);
        }

        private static string Describe(List<ShapedGlyph> glyphs)
        {
            var sb = new StringBuilder();
            foreach (var g in glyphs)
            {
                if (sb.Length > 0) sb.Append(' ');
                sb.Append(g.Glyph).Append('(').Append(g.XAdvance).Append(',').Append(g.XOffset).Append(',').Append(g.YOffset).Append(')');
            }
            return sb.ToString();
        }
    }
}
